name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: actions/setup-node@v2
      with:
        node-version: 12
    - name: info
      run: |
        pwd
        ls
        find
    - name: Build
      run: |
        make all
    - name: run open-version-pack
      run: |
        make f=build/ovpack.txt discover-pack
    - name: see results
      run: |
        cat build/ovpack.txt

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
      - run: npm config set git-tag-version false
      - run: npm config set commit-hooks false
      - run: npm version patch --force
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}