name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: info
      run: |
        pwd
        ls
        find
    - name: Build
      run: |
        make all
    - name: run open-version-pack
      run: |
        make f=build/ovpack.txt discover-pack
    - name: see results
      run: |
        cat build/ovpack.txt